version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    tty: true

  mysql:
      platform: linux/x86_64
      image: mysql:8
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_ARABITRARY: 1
      ports:
          - '81:80'
      links:
        - php
        - mysql

